spring.application.name=auth-service
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# JWT — generate a 256-bit Base64 key for production
jwt.secret=dGhpcylzYS1kZXYtc2VjcmV0LWtleS10aGF0LWlzLWxvbmctZW5vdWdoLTI1Ng==
jwt.expiration-ms=86400000
